// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qubetics/session/v3/session.proto

package v3

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	v1 "github.com/qubetics/qubetics-blockchain/v2/types/v1"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BaseSession struct {
	ID            uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccAddress    string                `protobuf:"bytes,2,opt,name=acc_address,json=accAddress,proto3" json:"acc_address,omitempty"`
	NodeAddress   string                `protobuf:"bytes,3,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	DownloadBytes cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=download_bytes,json=downloadBytes,proto3,customtype=cosmossdk.io/math.Int" json:"download_bytes"`
	UploadBytes   cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=upload_bytes,json=uploadBytes,proto3,customtype=cosmossdk.io/math.Int" json:"upload_bytes"`
	MaxBytes      cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=max_bytes,json=maxBytes,proto3,customtype=cosmossdk.io/math.Int" json:"max_bytes"`
	Duration      time.Duration         `protobuf:"bytes,7,opt,name=duration,proto3,stdduration" json:"duration"`
	MaxDuration   time.Duration         `protobuf:"bytes,8,opt,name=max_duration,json=maxDuration,proto3,stdduration" json:"max_duration"`
	Status        v1.Status             `protobuf:"varint,9,opt,name=status,proto3,enum=qubetics.types.v1.Status" json:"status,omitempty"`
	InactiveAt    time.Time             `protobuf:"bytes,10,opt,name=inactive_at,json=inactiveAt,proto3,stdtime" json:"inactive_at"`
	StartAt       time.Time             `protobuf:"bytes,11,opt,name=start_at,json=startAt,proto3,stdtime" json:"start_at"`
	StatusAt      time.Time             `protobuf:"bytes,12,opt,name=status_at,json=statusAt,proto3,stdtime" json:"status_at"`
}

func (m *BaseSession) Reset()         { *m = BaseSession{} }
func (m *BaseSession) String() string { return proto.CompactTextString(m) }
func (*BaseSession) ProtoMessage()    {}
func (*BaseSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_fea88556de6990aa, []int{0}
}
func (m *BaseSession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BaseSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BaseSession.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BaseSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSession.Merge(m, src)
}
func (m *BaseSession) XXX_Size() int {
	return m.Size()
}
func (m *BaseSession) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSession.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSession proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BaseSession)(nil), "qubetics.session.v3.BaseSession")
}

func init() { proto.RegisterFile("qubetics/session/v3/session.proto", fileDescriptor_fea88556de6990aa) }

var fileDescriptor_fea88556de6990aa = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xed, 0xd0, 0xa6, 0xc9, 0x3a, 0xf4, 0x60, 0xfe, 0xc8, 0x8d, 0x84, 0x9d, 0x72, 0xca,
	0x85, 0x5d, 0x35, 0xb9, 0x21, 0x21, 0x88, 0x15, 0x90, 0x7a, 0x75, 0x39, 0x71, 0x89, 0xd6, 0xeb,
	0xc5, 0x59, 0x35, 0xf6, 0x86, 0xec, 0xda, 0xa4, 0x6f, 0xd1, 0x23, 0x8f, 0xc0, 0x03, 0xf0, 0x10,
	0x39, 0xf6, 0x88, 0x38, 0x04, 0x70, 0x5e, 0x04, 0xad, 0x37, 0x6b, 0x21, 0xb8, 0xa4, 0xb7, 0xf1,
	0xcc, 0xf7, 0xfd, 0x66, 0xe4, 0xd9, 0x01, 0xe7, 0x9f, 0x8a, 0x98, 0x4a, 0x46, 0x04, 0x12, 0x54,
	0x08, 0xc6, 0x73, 0x54, 0x8e, 0x4d, 0x08, 0x97, 0x2b, 0x2e, 0xb9, 0xfb, 0xc8, 0x48, 0xa0, 0xc9,
	0x97, 0xe3, 0xfe, 0xe3, 0x94, 0xa7, 0xbc, 0xae, 0x23, 0x15, 0x69, 0x69, 0xdf, 0x4f, 0x39, 0x4f,
	0x17, 0x14, 0xd5, 0x5f, 0x71, 0xf1, 0x11, 0x25, 0xc5, 0x0a, 0xcb, 0x06, 0xd5, 0x0f, 0xfe, 0xad,
	0x4b, 0x96, 0x51, 0x21, 0x71, 0xb6, 0x34, 0x80, 0x66, 0x1c, 0x79, 0xb3, 0xa4, 0x02, 0x95, 0x17,
	0x48, 0x48, 0x2c, 0x0b, 0xa1, 0xeb, 0xcf, 0xbf, 0x1d, 0x03, 0x27, 0xc4, 0x82, 0x5e, 0xe9, 0x49,
	0xdc, 0xa7, 0xa0, 0xc5, 0x12, 0xcf, 0x1e, 0xd8, 0xc3, 0xa3, 0xb0, 0x5d, 0x6d, 0x83, 0xd6, 0xe5,
	0x34, 0x6a, 0xb1, 0xc4, 0x0d, 0x80, 0x83, 0x09, 0x99, 0xe1, 0x24, 0x59, 0x51, 0x21, 0xbc, 0xd6,
	0xc0, 0x1e, 0x76, 0x23, 0x80, 0x09, 0x99, 0xe8, 0x8c, 0x7b, 0x0e, 0x7a, 0x39, 0x4f, 0x68, 0xa3,
	0x78, 0x50, 0x2b, 0x1c, 0x95, 0x33, 0x92, 0x29, 0x38, 0x4d, 0xf8, 0xe7, 0x7c, 0xc1, 0x71, 0x32,
	0x8b, 0x6f, 0x24, 0x15, 0xde, 0x91, 0x12, 0x85, 0xcf, 0x36, 0xdb, 0xc0, 0xfa, 0xb1, 0x0d, 0x9e,
	0x10, 0x2e, 0x32, 0x2e, 0x44, 0x72, 0x0d, 0x19, 0x47, 0x19, 0x96, 0x73, 0x78, 0x99, 0xcb, 0xe8,
	0xa1, 0x31, 0x85, 0xca, 0xe3, 0xbe, 0x01, 0xbd, 0x62, 0xf9, 0x17, 0xe3, 0xf8, 0x10, 0x86, 0xa3,
	0x2d, 0x9a, 0xf0, 0x12, 0x74, 0x33, 0xbc, 0xde, 0xdb, 0xdb, 0x87, 0xd8, 0x3b, 0x19, 0x5e, 0x6b,
	0xef, 0x6b, 0xd0, 0x31, 0x2b, 0xf0, 0x4e, 0x06, 0xf6, 0xd0, 0x19, 0x9d, 0x41, 0xbd, 0x03, 0x68,
	0x76, 0x00, 0xa7, 0x7b, 0x41, 0xd8, 0x51, 0xd4, 0x2f, 0x3f, 0x03, 0x3b, 0x6a, 0x4c, 0xee, 0x3b,
	0xd0, 0x53, 0xcd, 0x1b, 0x48, 0xe7, 0x70, 0x88, 0x93, 0xe1, 0xb5, 0x49, 0xbb, 0x17, 0xa0, 0xad,
	0x17, 0xe9, 0x75, 0x07, 0xf6, 0xf0, 0x74, 0x74, 0x06, 0x9b, 0x57, 0x55, 0x6f, 0x1a, 0x96, 0x17,
	0xf0, 0xaa, 0x16, 0x44, 0x7b, 0xa1, 0xfb, 0x16, 0x38, 0x2c, 0xc7, 0x44, 0xb2, 0x92, 0xce, 0xb0,
	0xf4, 0x40, 0xdd, 0xb9, 0xff, 0x5f, 0xe7, 0xf7, 0xe6, 0x09, 0xe9, 0xd6, 0xb7, 0xaa, 0x35, 0x30,
	0xc6, 0x89, 0x54, 0xbf, 0x40, 0x48, 0xbc, 0x92, 0x8a, 0xe1, 0xdc, 0x83, 0x71, 0x52, 0xbb, 0x26,
	0xd2, 0x9d, 0x80, 0xae, 0x9e, 0x48, 0x11, 0x7a, 0xf7, 0x20, 0x74, 0xb4, 0x6d, 0x22, 0xc3, 0xd9,
	0xe6, 0xb7, 0x6f, 0x7d, 0xad, 0x7c, 0x6b, 0x53, 0xf9, 0xf6, 0x5d, 0xe5, 0xdb, 0xbf, 0x2a, 0xdf,
	0xbe, 0xdd, 0xf9, 0xd6, 0xdd, 0xce, 0xb7, 0xbe, 0xef, 0x7c, 0xeb, 0xc3, 0xab, 0x94, 0xc9, 0x79,
	0x11, 0x43, 0xc2, 0x33, 0xd4, 0xdc, 0x80, 0x09, 0x5e, 0xc4, 0x0b, 0x4e, 0xae, 0xc9, 0x1c, 0xb3,
	0x1c, 0x95, 0x23, 0xb4, 0x6e, 0x6e, 0x75, 0x7f, 0x24, 0xe3, 0xb8, 0x5d, 0x0f, 0x32, 0xfe, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xac, 0x5f, 0x0b, 0x35, 0xcf, 0x03, 0x00, 0x00,
}

func (m *BaseSession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BaseSession) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BaseSession) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StatusAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StatusAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintSession(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x62
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintSession(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x5a
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.InactiveAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.InactiveAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintSession(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x52
	if m.Status != 0 {
		i = encodeVarintSession(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x48
	}
	n4, err4 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxDuration):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintSession(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x42
	n5, err5 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Duration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Duration):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintSession(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x3a
	{
		size := m.MaxBytes.Size()
		i -= size
		if _, err := m.MaxBytes.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSession(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.UploadBytes.Size()
		i -= size
		if _, err := m.UploadBytes.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSession(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.DownloadBytes.Size()
		i -= size
		if _, err := m.DownloadBytes.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSession(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.NodeAddress) > 0 {
		i -= len(m.NodeAddress)
		copy(dAtA[i:], m.NodeAddress)
		i = encodeVarintSession(dAtA, i, uint64(len(m.NodeAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccAddress) > 0 {
		i -= len(m.AccAddress)
		copy(dAtA[i:], m.AccAddress)
		i = encodeVarintSession(dAtA, i, uint64(len(m.AccAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintSession(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSession(dAtA []byte, offset int, v uint64) int {
	offset -= sovSession(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BaseSession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovSession(uint64(m.ID))
	}
	l = len(m.AccAddress)
	if l > 0 {
		n += 1 + l + sovSession(uint64(l))
	}
	l = len(m.NodeAddress)
	if l > 0 {
		n += 1 + l + sovSession(uint64(l))
	}
	l = m.DownloadBytes.Size()
	n += 1 + l + sovSession(uint64(l))
	l = m.UploadBytes.Size()
	n += 1 + l + sovSession(uint64(l))
	l = m.MaxBytes.Size()
	n += 1 + l + sovSession(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Duration)
	n += 1 + l + sovSession(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxDuration)
	n += 1 + l + sovSession(uint64(l))
	if m.Status != 0 {
		n += 1 + sovSession(uint64(m.Status))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.InactiveAt)
	n += 1 + l + sovSession(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartAt)
	n += 1 + l + sovSession(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StatusAt)
	n += 1 + l + sovSession(uint64(l))
	return n
}

func sovSession(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSession(x uint64) (n int) {
	return sovSession(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BaseSession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSession
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BaseSession: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BaseSession: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownloadBytes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DownloadBytes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadBytes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UploadBytes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBytes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBytes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Duration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= v1.Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InactiveAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.InactiveAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSession
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSession
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSession
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StatusAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSession(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSession
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSession(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSession
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSession
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSession
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSession
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSession
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSession
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSession        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSession          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSession = fmt.Errorf("proto: unexpected end of group")
)
